### PR TITLE
Author details added in theme

### PR DESCRIPTION
**Pull request by adishap**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/hugo-dgraph-theme/1)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[README.md, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUau8t-qzkc_bu4cG3j:-KUau8t-qzkc_bu4cG3k:b734u00) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/README.md#L31)):_

> ``` Markdown
> ## Show Author And Editor Details in Blogs
> 
> * To add `author` name, create a file `author_name.html` in `layouts/partials/` and add name in format:
> ```

Maybe have these comments in the sample file and mention that you have examples there.

---

_[layouts/_default/single.html, line 276 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauOZimhKTxShz42L6:-KUauOZjz-BE8pYVZ2f3:b8ds5gs) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/_default/single.html#L276)):_

> ``` HTML
>               <div class="share">
>                 <ul class="share__list">
>                   <li class="share__item"><a href="https://twitter.com/share?text={{ .Title | safeHTML}}&amp;url={{ .Permalink }}&amp;via=dgraphlabs" class="share__link">
> ```

Shouldn't this come from the config? This shouldn't be hardcoded into the theme.

---

_[layouts/_default/single.html, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauYXDeREdnJVuVRVf:-KUauYXDeREdnJVuVRVg:b-kxtsxq) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/b8f3df0a7dbccc351193b03a4c2f4ac6cb1f8ce2/layouts/_default/single.html#L333)):_

> ``` HTML
>   <script type="text/javascript">hljs.initHighlightingOnLoad();</script>-
> 
>   {{if .Site.Params.discourse}}
> ```

Why remove this?

---

_[layouts/_default/single.html, line 334 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauW-TdOqWv0GcHOHU:-KUauW-UT1moHFat7Z7_:b-yzyou3) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/_default/single.html#L334)):_

> ``` HTML
> 
>   <script type="text/javascript">
>     DiscourseEmbed = { discourseUrl: 'https://discuss.dgraph.io/',discourseEmbedUrl: '{{ .Permalink }}' };
> ```

Why we hard coded all this stuff?

---

_[layouts/partials/author_name.html, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUau_rfVuC5bpaLywrk:-KUau_rfVuC5bpaLywrl:b-4gotp4) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/partials/author_name.html#L1)):_

> ``` HTML
> {{if eq .Params.author "mrjn" }}Manish Rai Jain
> ```

Have a comment that this is how the sample file would look like.

---

_[layouts/partials/author_profile.html, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauh9x4ci9R4rf4LUs:-KUauh9x4ci9R4rf4LUt:b-dg1iad) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/partials/author_profile.html#L1)):_

> ``` HTML
> {{if eq .Params.author "mrjn" }}
> ```

Is there someway that you can abstract out the stuff in author_profile.html and editor_profile.html and make the whole thing more DRY by not repeating stuff?

Maybe having another partial.

---

_[layouts/partials/footer.html, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauwJXaYTXjwLWkOP1:-KUauwJXaYTXjwLWkOP2:bhzh8nq) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/b8f3df0a7dbccc351193b03a4c2f4ac6cb1f8ce2/layouts/partials/footer.html#L12)):_

> ``` HTML
>                       <h6 class="page-footer-nav__title">Community</h6>
>                       <ul class="page-footer-nav__list">
>                           {{if .Site.Params.github }}
> ```

Why are we hard coding all this stuff?

the idea is that someone should be able to supply parameters in config.toml and use it for their blog.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1)_

**Comment by adishap** [comment]
Review status: 1 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

_[README.md, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUau8t-qzkc_bu4cG3j:-KUeRKw1RywhsMVN6GRM:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/README.md#L31)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Maybe have these comments in the sample file and mention that you have examples there.
> </details>
> Done.

---

_[layouts/_default/single.html, line 276 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauOZimhKTxShz42L6:-KUb8i56f-j8URvG8XGg:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/_default/single.html#L276)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Shouldn't this come from the config? This shouldn't be hardcoded into the theme.
> </details>
> Done.

---

_[layouts/_default/single.html, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauYXDeREdnJVuVRVf:-KUb8oLP2BfTb0UjH6Ek:b-nunydv) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/b8f3df0a7dbccc351193b03a4c2f4ac6cb1f8ce2/layouts/_default/single.html#L333)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Why remove this?
> </details>
> I removed extra four spaces from here.

---

_[layouts/_default/single.html, line 334 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauW-TdOqWv0GcHOHU:-KUb8l3PMEvDMe-sQsfY:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/_default/single.html#L334)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Why we hard coded all this stuff?
> </details>
> Done.

---

_[layouts/partials/author_name.html, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUau_rfVuC5bpaLywrk:-KUeSfbHKtH4darh2dsB:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/partials/author_name.html#L1)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Have a comment that this is how the sample file would look like.
> </details>
> Done.

---

_[layouts/partials/author_profile.html, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauh9x4ci9R4rf4LUs:-KUeSkblerdryXIlGs_4:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/160202a4b7421c5f7199a3447c77cccaca1a97fb/layouts/partials/author_profile.html#L1)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Is there someway that you can abstract out the stuff in author_profile.html and editor_profile.html and make the whole thing more DRY by not repeating stuff?
> 
> Maybe having another partial.
> </details>
> Done.

---

_[layouts/partials/footer.html, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUauwJXaYTXjwLWkOP1:-KUeSrksxfitAhB7hCBZ:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/b8f3df0a7dbccc351193b03a4c2f4ac6cb1f8ce2/layouts/partials/footer.html#L12)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Why are we hard coding all this stuff?
> 
> the idea is that someone should be able to supply parameters in config.toml and use it for their blog.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1)_

**Comment by pawanrawal** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[README.md, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjthl15vpDLAiCAGRR:-KUjthl15vpDLAiCAGRS:bcjvxk7) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/README.md#L31)):_

> ``` Markdown
> ## Show Author And Editor Details in Blogs
> 
> * To add `author` name, create a file `author_name.html` in `layouts/partials/` and add name in format:
> ```

Sentence is incomplete. In a format similar to what we have in layouts/partials/author_name.html etc ...

---

_[exampleSite/config.toml, line 22 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjtxbDQjA71kmFU-zP:-KUjtxbDQjA71kmFU-zQ:b-t846kn) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/exampleSite/config.toml#L22)):_

> ``` TOML
> 
>   # Website demo url, used on the top.
>   demo = "https://dgraph.io"
> ```

Thanks for abstracting this out.

---

_[layouts/_default/list.html, line 10 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUju7n634Min6GtdtRi:-KUju7n634Min6GtdtRj:b-cu126) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/layouts/_default/list.html#L10)):_

> ``` HTML
>           <ul class="article__list">
>           
>           {{ range (.Paginator 5).Pages }}
> ```

So why isn't this a config?

---

_[layouts/partials/author_detail.html, line 27 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjuOr50LmldLiUL0cq:-KUjuOr50LmldLiUL0cr:bx4mc5l) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/layouts/partials/author_detail.html#L27)):_

> ``` HTML
> -->
> 
> {{if eq .user "mrjn" }}
> ```

Actually, since we have provided an example we don't need to have actual bio,images for Me and Manish.

---

_[layouts/partials/author_profile.html, line 9 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjunSYbEBiGHP4xa6q:-KUjunSZzLFZlon___68:b-t47erd) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/layouts/partials/author_profile.html#L9)):_

> ``` HTML
>           <span class="article-author__title">Author</span>
>       </h4>
>       {{partial "author_detail.html" (dict "user" .Params.author)}}
> ```

That that just cleans up so much stuff.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1)_

**Comment by adishap** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[README.md, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjthl15vpDLAiCAGRR:-KUp4bVffyShCNEH4DY7:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/README.md#L31)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Sentence is incomplete. In a format similar to what we have in layouts/partials/author_name.html etc ...
> </details>
> Done.

---

_[layouts/_default/list.html, line 10 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUju7n634Min6GtdtRi:-KUp4fT6cilOhmJDYrVR:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/layouts/_default/list.html#L10)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> So why isn't this a config?
> </details>
> Done.

---

_[layouts/partials/author_detail.html, line 27 at r2](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1#-KUjuOr50LmldLiUL0cq:-KUp7SeI9RhRDrh7f-kx:b-896fix) ([raw file](https://github.com/dgraph-io/hugo-dgraph-theme/blob/bcea176ce83adc9c76ddd6af1c45490ab1b62cca/layouts/partials/author_detail.html#L27)):_
<details><summary>

<i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>



> Actually, since we have provided an example we don't need to have actual bio,images for Me and Manish.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/hugo-dgraph-theme/1)_

**Pull request closed without merging**
